name: ci
run-name: ${{ github.actor }} is running ci

on: [push, pull_request]

jobs:
  build-docker-image:
    name: "Polaris Bulk Patron Update Docker"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Run build.bash
        env:
          BLD_DOCKER_IMAGE: polaris-bulk-patron-update
          CR_HOST: ${{secrets.CR_HOST}}
          CR_OWNER: ${{secrets.CR_OWNER}}
          CR_PASSWORD: ${{secrets.CR_PASSWORD}}
          CR_USER: ${{secrets.CR_USER}}
          GHCR_OWNER: ${{secrets.GHCR_OWNER}}
          GHCR_PAT: ${{secrets.GHCR_PAT}}
          GHCR_USER: ${{secrets.GHCR_USER}}
        run: ./build.bash -p

      - uses: actions/upload-artifact@v6
        with:
          compression-level: 9
          if-no-files-found: ignore
          name: PolarisBulkPatronUpdate
          path: package/*
